name: Validate Changes
run-name: Run validation against Scratch Org
on: workflow_dispatch
jobs:
   run-validation:
      environment: IT
      name: Run Validation job
      runs-on: ubuntu-22.04
      steps:
         -  name: Download files from repository
            uses: actions/checkout@v4
         -  name: Install SF CLI
            run: npm install --global @salesforce/cli@~2.120.3
         -  name: Authenticate on DevHub
            run: |
               echo "${{ secrets.AUTH_FILE }}" > ./authFile
               sf org login sfdx-url --sfdx-url-file ./authFile -a autfileconnection
         -  name: Create log connection file
            run: |
               sf org display --verbose -o autfileconnection > ./myConncetion.txt
         -  name: Upload log connection file
            uses: actions/upload-artifact@v6
            with: 
               name: orgDetails
               path: ./myConncetion.txt
         # to test without creation SO
         -  name: Create Sratch Org
            ## Will simulate Scratch Org creation during development, so it doesn't consume the limits
            ## run: sf org scratch create -w 10 -a validationSO -f config/project-scratch-def.json -v autfileconnection
            run: echo "creating SO"