name: Run validation workflow
run-name: Validate, test and deploy
on: workflow_dispatch
jobs:
   run-validation:
      environment: IT
      name: Run Validation job
      runs-on: ubuntu-22.04
      steps:
         -  name: Download files from repository
            uses: actions/checkout@v4
         -  name: Install SF CLI
            run: npm install --global @salesforce/cli@~2.112.0
         -  name: Secrets
            run: |
               echo "DEV_HUB_JWT: ${{ secrets.DEV_HUB_JWT }}"
               echo "DEV_HUB_CLIENT_ID: ${{ secrets.DEV_HUB_CLIENT_ID }}"
               echo "DEV_HUB_INSTANCE_URL: ${{ vars.DEV_HUB_INSTANCE_URL }}"
               echo "DEV_HUB_USERNAME: ${{ vars.DEV_HUB_USERNAME }}"
         -  name: Authenticate on DevHub
            run: |
               echo "${{ secrets.AUTH_FILE }}" | sf org login sfdx-url -u --alias devhub -d
         -  name: Create Sratch Org
            run: sf org scratch create --no-track-source -y 1 -v devhub -w 10 -f config/project-scratch-def.json -a validationScratchOrg